// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcodkxsulqoabihlcagu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjb2RreHN1bHFvYWJpaGxjYWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDEyMTYsImV4cCI6MjA2NDE3NzIxNn0.EY-cM2XjYbp64Wki6g21bYYnrk3nQ0Kgm6HiYAnTIDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);